apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: manila-csi-driver-controller-metrics-serving-cert
  labels:
    app: manila-csi-driver-controller-metrics
  name: manila-csi-driver-controller-metrics
  namespace: openshift-cluster-csi-drivers
spec:
  ports:
  - name: provisioner-m
    port: 443
    protocol: TCP
    targetPort: provisioner-m
  - name: snapshotter-m
    port: 444
    protocol: TCP
    targetPort: snapshotter-m
  selector:
    app: manila-csi-driver-controller
  sessionAffinity: None
  type: ClusterIP
